### ISSUE TITLE
Expired license

### ISSUE THREAD

**Issue by anasbousselham** [c9845/licensekeys#1]
Hi,
How about the expired license check? can you please update `licenseData.Verify` to add some expired license verification?
Thank you.

**Comment by c9845** [comment]
This is something I have already implemented in a private fork of this repo, although via a separate `Expired()` function.  I kept the checking of expiration separate from verification since verification deals only with checking the signature.

I will copy over this expiration-checking functionality (as well as a ton of other changes).  Give me a week or so.

**Comment by c9845** [comment]
Please see latest changes.

**Comment by anasbousselham** [comment]
Hi,
sorry but I don't understand how to call ExpiresIn and Expires func. can you please update the client exp. ?
Thank you.

**Comment by c9845** [comment]
```golang
//Read license from file...
f, _:= licensefile.Read("/path/to/your/license/file", licensefile.FileFormatYAML)

//Verify, signature only...
err := f.VerifySignature(publicKey, keyPairAlgo)
if err == ErrBadSignature {
    //Handle invalid signature.
} else if err != nil {
    //Some other error.
}

//Signature is valid, check if license is expired...
expired, err := f.Expired()
if err != nil {
    //Handle error.
}
if expired {
    //Handle expired license.
}
```

You can also do....
```golang
//Read license from file...
f, _:= licensefile.Read("/path/to/your/license/file", licensefile.FileFormatYAML)

//Verify signature and check if license is expired, all at once.
err := f.Verify(publicKey, keyPairAlgo)
if err == ErrBadSignature {
    //Handle invalid signature.
} else if err == ErrExpired {
    //Handle expired license.
} else if err != nil {
    //Handle other error.
}
```

**Comment by anasbousselham** [comment]
Thanks, but I have `licenseData.Expired undefined` licenseData = licensefile.Read

**Comment by c9845** [comment]
You need to update to the latest beta release.  As of just now, `go get github.com/c9834/licensekeys/v2@v2.1.0-beta2`.

**Comment by anasbousselham** [comment]
remote: Repository not found.
        fatal: repository 'https://github.com/c9834/licensekeys/' not found

**Comment by c9845** [comment]
@anasbousselham Come on, for someone who notes themselves as "Systems Administrator, Cybersecurity, Ethical Hacker", I would have though you would be able to diagnose a typo.  c9845 vs c9843 in the URL.

`go get github.com/c9845/licensekeys/v2@v2.1.0-beta2`

**Comment by anasbousselham** [comment]
sorry but still not working, It's not my first time working with go, I have a lot off app with it. something is wrong..

**Comment by anasbousselham** [comment]
c9834 --> c9835

**Comment by c9845** [comment]
`go get github.com/c9845/licensekeys/v2@v2.1.0-beta2` works.  I just tested it half a dozen times across multiple machines.

**Comment by c9845** [comment]
Use Expired(), ExpiresIn(), and ExpiresInDays() funcs parts of v2.1.0 release.

**Comment by c9845** [comment]
@anasbousselham Please create a separate issue for this and clarify what you are looking for.  I did so for you.  Please see my reply and please provide more info.
