### ISSUE TITLE
License assigned to specific mac address or unique machine id.

### ISSUE THREAD

**Issue by c9845** [c9845/licensekeys#3]
How about  license to specific mac address or unique machine id `/etc/machine-id` !

_Originally posted by @anasbousselham in https://github.com/c9845/licensekeys/issues/1#issuecomment-1520270765_

**Comment by c9845** [comment]
@anasbousselham From the sounds of what you wrote, you should use the "Custom Fields" functionality for this.  

- Create a Text named something like "Assigned To MAC Address" or "Assigned To Machine ID".
- Create a license, providing the MAC or ID you want to assign the license to.
- Distribute the license.
- In your client-side code, check the MAC or Machine ID after validating the license using the `ExtraAsString` func.

**Comment by anasbousselham** [comment]
thanks, Good Idea

**Comment by c9845** [comment]
Fixed in latest version v2.1.1.
